### ISSUE TITLE
Hosting側から正しくJSONを送信できない問題

### ISSUE THREAD

**Issue by shun-harutaro** [shun-harutaro/tosho-card#15]

**Comment by shun-harutaro** [comment]
application/json で送らないと解析できないらしい

**Comment by shun-harutaro** [comment]
`Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 402, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 268, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker_v2.py", line 261, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 45, in handler id_form.send_keys(request_json['id']) TypeError: 'NoneType' object is not subscriptable`

**Comment by shun-harutaro** [comment]
完全にCORS(functions側)の問題だった。解決。
